project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
    mermaid:
      enabled: true
    bibliography: reference.bib


